### ISSUE TITLE
'cave reset-db' is not listed as cmd in --help

### ISSUE THREAD

**Issue by mitrussell** [MIT-CAVE/cave_cli#103]
When running `cave --help`, under "Global Flags" the following example is used:
``-y`:                     Automatically answer (bypass) any confirmation prompts with `y`.
                              - Note: This is useful for scripting
                              - EG: `cave reset-db -y`
`

But when you look at the commands `reset-db` is not listed in the help docs.

**Comment by connor-makowski** [comment]
I should fix this. `cave reset` = `cave reset-db`.

**Comment by connor-makowski** [comment]
Both of these were kept for backwards compatibility.

**Comment by connor-makowski** [comment]
Closing with https://github.com/MIT-CAVE/cave_cli/commit/4dc925917da2ddfcc8ac66f4ee12fb3c0c2fe62e
