### ISSUE TITLE
Return support for saving mapbox token

### ISSUE THREAD

**Issue by mrkwanzaa** [MIT-CAVE/cave_cli#120]
On `cave create` the cli was previously able to use a previously saved mapbox token. We can return this support by first asking the user Do you want to use mapbox(y/n)?: and then allowing them to leave the token blank to used the saved one (or something similar).

**Comment by maxtkc** [comment]
Fixed in https://github.com/MIT-CAVE/cave_cli/pull/123


![Image](https://github.com/MIT-CAVE/cave_cli/assets/18196879/b52c1621-7187-4213-8497-c6e4198e0f67)

or



![Image](https://github.com/MIT-CAVE/cave_cli/assets/18196879/77103fde-168d-4253-9fa4-02136508af7e)
