### ISSUE TITLE
Add debugging notes to Windows Installation README

### ISSUE THREAD

**Issue by brianzheng205** [MIT-CAVE/cave_cli#127]

**Comment by connor-makowski** [comment]
Tagging commit: https://github.com/MIT-CAVE/cave_cli/commit/a7c9069ce2ec29e00a00c83f9810d1081888745c

**Comment by connor-makowski** [comment]
@brianzheng205 lets try to be a bit more explicit.

EG:

Notes: 
    - You should be using Ubuntu 22.04
    - If you are using VS Code, you can easily open WSL based folders with the `code` command. For example while in your project directory: `code .`

**Comment by brianzheng205** [comment]
@connor-makowski updated!

**Comment by connor-makowski** [comment]
Looks good. Merging back into 2.2.0 since its just docs. Then will merge into main. See: https://github.com/MIT-CAVE/cave_cli/pull/128

**Comment by luisvasq** [comment]
Closing this with #128.
