### ISSUE TITLE
New Function: cave update-environment

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_cli#28]
The main idea is that I want to be able to add requirements (or items in setup.py) and then have the cave cli be able to install those for me.

Probably it is best to just nuke the old venv, and reinstall.

See:
https://github.com/MIT-CAVE/cave_app/blob/0.1.0/cave_api/README.md#adding-requirements-to-the-api

Again, take some freedoms here to keep things generalizable. Also, I am not tied to the name. Feel free to pick something better.

**Comment by mrkwanzaa** [comment]
I am going to call this one. `cave install`. I'll update the cave_app readme.
