### ISSUE TITLE
Verify function on a mac

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_cli#8]
There are some existing issues on a mac when using sed during cave create.

Lets see if there are any other bugs we can find in there when using a mac.

**Comment by mrkwanzaa** [comment]
Should be working on mac now. @connor-makowski can you verify that everything is working properly on apple silicon? I don't have a device to test that with.

**Comment by connor-makowski** [comment]
Not finding any bugs now. Thanks @mrkwanzaa
